name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 1. Установка Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Шаг 2. Установка зависимостей
      - name: Install dependencies
        run: bun ci

      # Шаг 3. Сборка проекта
      - name: Build project
        run: bun run build

      # Установка yc CLI
      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          source $HOME/.bashrc
          which yc
          yc --version
          echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > key.json
          yc config set service-account-key key.json
          yc config list  # проверка конфигурации
          yc storage cp --recursive doc_build/* s3://cloika-tavern/
