name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1. Установка Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Debug Check repository structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Files in root:"
          find . -maxdepth 1 -type f -printf "%f\n"

      # Шаг 2. Установка зависимостей
      - name: Install dependencies
        run: bun install

      # Шаг 3. Сборка проекта
      - name: Build project
        run: bun run build

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo 'source /home/runner/.yandex-cloud/completion.bash' >> ~/.bashrc

      - name: Authenticate with Yandex Cloud
        run: echo "${{ secrets.YC_SECRET_ACCESS_KEY }}" > key.json && yc config set service-account-key key.json

      - name: Upload to Storage
        run: yc storage cp --recursive doc_build/* s3://cloika-tavern/
