name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 1. Установка Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Шаг 2. Установка зависимостей
      - name: Install dependencies
        run: bun ci

      # Шаг 3. Сборка проекта
      - name: Build project
        run: bun run build

      - name: S3 Sync
        uses: yc-actions/yc-obj-storage-upload@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_CRED_JSON }}
          bucket: ${{ secrets.BUCKET_NAME }}
          root: ./doc_build
          include: |
            **
