name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 1. Установка Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Шаг 2. Установка зависимостей
      - name: Install dependencies
        run: bun ci

      # Шаг 3. Сборка проекта
      - name: Build project
        run: bun run build

      - name: Install Yandex Cloud CLI
        run: |
          # Установка (подавляем вывод инструкций)
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash > /dev/null 2>&1

          # Применяем изменения в PATH
          source $HOME/.bashrc

          # Проверка установки
          which yc || { echo "yc not found!"; exit 1; }
          yc --version

      - name: Authenticate and Upload
        run: |
          # Сохраняем ключ сервисного аккаунта
          echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > key.json

          # Настройка YC CLI
          yc config set service-account-key key.json
          yc config list

          # Загрузка файлов
          yc storage cp --recursive doc_build/* s3://cloika-tavern/
