name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 1. Установка Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Шаг 2. Установка зависимостей
      - name: Install dependencies
        run: bun ci

      # Шаг 3. Сборка проекта
      - name: Build project
        run: bun run build

      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1 # Фиксированная версия!
        with:
          args: --acl public-read --sse AES256 --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "doc_build/"
          S3_ENDPOINT: "storage.yandexcloud.net"
          AWS_REGION: "ru-central1"
