name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1. Установка Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Шаг 2. Установка зависимостей
      - name: Install dependencies
        run: bun install

      # Шаг 3. Сборка проекта
      - name: Build project
        run: bun run build

      # Шаг 4. Выкладка в Yandex Cloud (в бакет cloika-tavern)
      - name: Deploy to Yandex Cloud Storage
        uses: yandex-cloud/yc-actions/storage-upload@v1
        with:
          service-account-key: ${{ secrets.YC_SECRET_ACCESS_KEY }}
          src: doc_build/
          dst: s3://cloika-tavern/
          recursive: true
