name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 1. Установка Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Шаг 2. Установка зависимостей
      - name: Install dependencies
        run: bun ci

      # Шаг 3. Сборка проекта
      - name: Build project
        run: bun run build

      - name: Install Yandex Cloud CLI
        run: |
          # 1. Определяем версию (можно заменить на конкретную, например 0.192.0)
          VERSION=$(curl -s https://api.github.com/repos/yandex-cloud/yc-cli/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

          # 2. Скачиваем архив
          curl -o yc-cli.tar.gz -L "https://github.com/yandex-cloud/yc-cli/releases/download/${VERSION}/yc-cli_${VERSION}_linux_amd64.tar.gz"

          # 3. Распаковываем в домашнюю директорию
          tar -xzf yc-cli.tar.gz -C $HOME/.yandex-cloud --strip-components=1

          # 4. Добавляем в PATH
          echo "$HOME/.yandex-cloud" >> $GITHUB_PATH

          # 5. Проверяем
          yc --version

      - name: Authenticate and Upload
        run: |
          # Сохраняем ключ сервисного аккаунта
          echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > key.json

          # Настройка YC CLI
          yc config set service-account-key key.json
          yc config list

          # Загрузка файлов
          yc storage cp --recursive doc_build/* s3://cloika-tavern/
